[workspace]
members = ["candidate-pipeline", "home-mixer", "thunder"]
resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[workspace.package]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
candidate-pipeline = {path = "candidate-pipeline"}
home-mixer = {path = "home-mixer"}
thunder = {path = "thunder"}
anyhow = "1.0"
axum = { version = "0.8", features = ["macros", "http2"] }
axum-extra = { version = "0.12", features = ["typed-header"] }
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
futures = "0.3"
headers = "0.4"
jsonwebtoken = { version = "10.2", features = ["rust_crypto"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "chrono", "ipnet"] }
tokio = { version = "1.48", features = ["full"] }
tower = { version = "0.5", features = [
    "util",
    "timeout",
    "limit",
    "load-shed",
    "steer",
    "filter",
] }
tower-http = { version = "0.6", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "serde_json"] }
validator = { version = "0.20", features = ["derive"] }
thiserror = { version = "2.0" }
client-ip = "0.1"
phonenumber = "0.3"
sha2 = "0.10"
hex = "0.4"
rsa = { version = "0.9", features = ["sha2", "pem", "pkcs5", "default"] }
rand = "0.9"
pkcs8 = { version = "0.10", features = ["std", "alloc", "pem", "encryption"] }
config = "0.15"
sonyflake = "0.4"
rs-snowflake = "0.6"
twilio = { version = "1.1" }
redis = { version = "1.0", features = ["tokio-comp"] }
regex = "1"
dirs = "6"
base64 = "0.22"
strfmt = "0.2"
tera = "1.20"
ua-parser = "0.2"
cookie = "0.18"
http = "1.4"
accept-language = "3.1"
phf = { version = "0.13", features = ["macros"] }
strum = "0.27"
strum_macros = "0.27"
tonic = "0.14.2"
tonic-reflection = "0.14.2"
prost = "0.14.3"
clap = { version = "4.5.54", features = ["derive"] }
log = "0.4.29"
dashmap = "6.1.0"